Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 12
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job counts:
	count	jobs
	1	all
	1	dskForward
	1	dskForwardOutput
	1	dskForwardOutputSort
	1	filterOut_forward
	1	forward_TmCalculate
	1	splitFiles
	7
Select jobs to execute...

[Fri Mar  5 11:35:17 2021]
rule splitFiles:
    input: /datater/wu/data/msa/zika.msa.fasta
    output: /datater/wu/data/splitFiles/zika/forward/{*}.fasta (dynamic), /datater/wu/data/splitFiles/zika/reverse/{*}.fasta (dynamic)
    jobid: 3
    wildcards: sample=zika

Subsequent jobs will be added dynamically depending on the output of this job
[Fri Mar  5 11:35:17 2021]
Error in rule splitFiles:
    jobid: 3
    output: /datater/wu/data/splitFiles/zika/forward/{*}.fasta (dynamic), /datater/wu/data/splitFiles/zika/reverse/{*}.fasta (dynamic)

RuleException:
URLError in line 12 of /datater/wu/stage_m2/rules/splitFiles.smk:
<urlopen error [Errno 2] No such file or directory: '/datater/wu/stage_m2/rules/scripts/overlap_segs.py'>
  File "/datater/wu/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2326, in run_wrapper
  File "/datater/wu/stage_m2/rules/splitFiles.smk", line 12, in __rule_splitFiles
  File "/datater/wu/miniconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 214, in urlopen
  File "/datater/wu/miniconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 517, in open
  File "/datater/wu/miniconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 534, in _open
  File "/datater/wu/miniconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 494, in _call_chain
  File "/datater/wu/miniconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 1481, in file_open
  File "/datater/wu/miniconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 1520, in open_local_file
  File "/datater/wu/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/datater/wu/miniconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/datater/wu/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/datater/wu/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2357, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /datater/wu/stage_m2/.snakemake/log/2021-03-05T113516.876837.snakemake.log
